<a href="https://colab.research.google.com/github/vieirapav/R/blob/master/1Getting_Started_with_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
from pandas import Series

In [ ]:
#Create a simple Variable Series
s1 = Series([5,10,15,20])
print(s1)


0     5
1    10
2    15
3    20
dtype: int64


In [ ]:
#Finding the values of s1
print(s1.values)

[ 5 10 15 20]


In [ ]:
#Finding when start,stop and steps in s1
print(s1.index)
#Finding how many values exist in s1
print(s1.index.values)

RangeIndex(start=0, stop=4, step=1)
[0 1 2 3]


In [ ]:
#Create Series from Numpy

revenue_array = np.array([400,300,200,100])
print(revenue_array)

[400 300 200 100]


In [ ]:
revenue_series = Series(revenue_array)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int64


In [ ]:
#Create Series with Custom Indexes

revenue = Series(revenue_array, index=['uber','ola','lyft','gojek'])
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int64


In [ ]:
#How acess the values 
revenue['ola']

200

In [ ]:
#Filter a Series based on conditions
print(revenue[revenue>250])

uber    400
ola     300
dtype: int64


In [ ]:
#Check if a element is in a series
print('ola' in revenue)

True


In [ ]:
#Function - to_dict()
revenue_dict = revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'lyft': 200, 'gojek': 100}


In [ ]:
#Addition of 2 series
print(revenue + revenue)

uber     800
ola      600
lyft     400
gojek    200
dtype: int64


In [ ]:
#Assign names to a series and its Index
revenue.name = "Company - Revenue"
revenue.index.name = "Company Name"
print(revenue)

Company Name
uber     400
ola      300
lyft     200
gojek    100
Name: Company - Revenue, dtype: int64
